project_id = "lunltoazmbezbfvozlfb"

[functions.create-session]
verify_jwt = false

[functions.create-lead]
verify_jwt = false

[functions.get-ip-info]
verify_jwt = false

[functions.send-lead-email]
verify_jwt = false

[functions.analyze-seo]
verify_jwt = false

[functions.analyze-competitor]
verify_jwt = false

[functions.validate-session]
verify_jwt = false

[functions.get-session-data]
verify_jwt = false

[functions.analyze-performance]
verify_jwt = false
